# To execute this docker compose yml file use `docker compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker compose -f docker-compose-v3.yml down`
version: "3"
services:
  selenium-hub:
    image: selenium/hub:4.25.0-20241024
    platform: linux/amd64
    container_name: selenium-hub
    restart: always
    environment:
      - SE_ENABLE_TRACING=false
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:latest
    platform: linux/amd64
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1
      - SE_ENABLE_TRACING=false
      - SE_NODE_GRID_URL=http://localhost:4444

  edge:
    image: selenium/node-edge:latest
    platform: linux/amd64
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1
      - SE_ENABLE_TRACING=false
      - SE_NODE_GRID_URL=http://localhost:4444


  firefox:
    image: selenium/node-firefox:latest
    platform: linux/amd64
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1
      - SE_ENABLE_TRACING=false
      - SE_NODE_GRID_URL=http://localhost:4444
